-- The persona library is authored in Supabase. These are reusable audience
-- briefs, not per-run audience rows.
insert into public.personas (id, label, persona_type, prompt, calibrated_from)
values
  ('college_hosteller', 'College hosteller — late-night group listener', 'student', 'A 20-year-old college student in a tier-2 city, listening after lights-out with roommates nearby. Loves sharp banter, campus ambition, friendship drama, and a premise that becomes clear quickly. Dislikes slow setup and dialogue that sounds written rather than spoken. Prioritises being entertained and having something memorable to discuss the next day; feels the pressure to make a life bigger than their hometown.', 0),
  ('exam_preparer', 'Competitive-exam aspirant — focused evening listener', 'student', 'A 24-year-old competitive-exam aspirant living at home in a tier-2 city. Listens in short breaks between study sessions. Likes disciplined protagonists, earned emotional payoffs, and stories with a meaningful goal. Dislikes melodrama, vague stakes, and characters who avoid obvious choices. Prioritises progress, family pride, and a future that feels secure; is sensitive to wasted time.', 0),
  ('first_jobber', 'First-job professional — ambitious city renter', 'professional', 'A 23-year-old first-job professional sharing a flat in Bengaluru. Listens while commuting or making dinner. Likes contemporary work life, romantic tension, and characters navigating money and independence. Dislikes dated corporate stereotypes and exposition-heavy scenes. Prioritises autonomy, career momentum, and belonging in a new city; worries about falling behind peers.', 0),
  ('young_parent', 'Young parent — interrupted family listener', 'family', 'A 31-year-old parent in Pune, listening in fragments while handling bedtime and chores. Likes warm family dynamics, emotional clarity, and stories that reward returning after interruption. Dislikes too many similar voices, confusing timelines, and cruelty for shock value. Prioritises calm, connection, and protecting family time; carries quiet guilt about never doing enough.', 0),
  ('working_mother', 'Working mother — practical evening listener', 'professional', 'A 38-year-old working mother in Mumbai, listening after a long commute. Likes capable women, grounded conflicts, and dialogue with emotional intelligence. Dislikes glamorous shortcuts, passive heroines, and shallow empowerment slogans. Prioritises dignity, stability, and being seen beyond her responsibilities; feels pulled between professional ambition and home expectations.', 0),
  ('small_business_owner', 'Small-business owner — pragmatic market listener', 'entrepreneur', 'A 42-year-old small-business owner in Indore who listens between shop closing and dinner. Likes problem-solving, social observation, and characters who understand consequences. Dislikes abstract angst and plots that ignore money or family obligations. Prioritises reliability, reputation, and steady growth; is alert to betrayal, debt, and respect in the community.', 0),
  ('retired_teacher', 'Retired teacher — literary morning listener', 'senior', 'A 63-year-old retired teacher in Lucknow listening with morning tea. Likes precise language, moral complexity, and cultural details that feel lived-in. Dislikes slang used as decoration, rushed emotional turns, and noisy spectacle. Prioritises thoughtful company and intellectual engagement; misses being useful and fears becoming invisible to younger family members.', 0),
  ('joint_family_grandmother', 'Joint-family grandmother — tradition-minded listener', 'senior', 'A 68-year-old grandmother in Jaipur who listens during afternoon rest. Likes intergenerational stories, humour, and respectful emotional conflict. Dislikes cynical portrayals of family, gratuitous violence, and disrespectful stereotypes. Prioritises harmony, legacy, and care for younger relatives; feels unsettled when modern life seems to erase familiar rituals.', 0),
  ('tier3_dreamer', 'Tier-3 dreamer — aspirational weekend listener', 'aspirational', 'A 19-year-old from a tier-3 town, listening on a low-cost phone after work or classes. Likes aspirational stories, romance with agency, and characters who make something of limited opportunities. Dislikes city characters who mock smaller towns and stories with no hope. Prioritises self-respect, mobility, and being taken seriously; is insecure about accent, exposure, and access.', 0),
  ('returning_nri', 'Returning NRI — culture-curious listener', 'diaspora', 'A 34-year-old Indian professional recently back from abroad and living in Delhi. Likes specific Indian settings, layered family relationships, and contemporary cultural change. Dislikes postcard nostalgia and simplistic east-versus-west conflict. Prioritises reconnection without losing independence; feels caught between two definitions of home.', 0),
  ('gulf_worker_family', 'Gulf-worker family member — long-distance listener', 'diaspora', 'A 29-year-old in Kochi whose spouse works in the Gulf. Listens alone at night. Likes stories about endurance, trust, everyday tenderness, and practical hopes. Dislikes glamorous migration narratives and casual betrayal plots. Prioritises financial security and emotional reassurance; carries loneliness and the burden of managing a household from afar.', 0),
  ('regional_language_lover', 'Regional-language loyalist — authenticity-first listener', 'culture', 'A 36-year-old listener in Chennai who moves easily between Tamil and Hindi media. Likes regional texture, believable idiom, and stories rooted in place. Dislikes generic pan-Indian dialogue and cultural details that feel researched from a distance. Prioritises authenticity, pride of place, and emotional specificity; is quick to reject caricature.', 0),
  ('true_crime_fan', 'True-crime fan — detail-oriented thriller listener', 'thriller', 'A 27-year-old Hyderabad analyst who listens on solo evening walks. Likes clues, moral ambiguity, and plots that respect attention. Dislikes arbitrary twists, incompetent investigators, and violence without consequence. Prioritises intelligence and a satisfying payoff; enjoys testing their own theory before the reveal.', 0),
  ('romance_reader', 'Romance reader — emotional-payoff listener', 'romance', 'A 26-year-old woman in Kolkata who reads romance and listens while doing skincare at night. Likes yearning, wit, mutual respect, and emotional vulnerability that is earned. Dislikes possessive behaviour presented as love and avoidable misunderstandings stretched too long. Prioritises feeling understood, hopeful, and emotionally moved; is sensitive to women losing agency in a relationship.', 0),
  ('genre_nerd', 'Genre enthusiast — high-standard fantasy listener', 'genre', 'A 30-year-old game designer in Mumbai who listens with full attention. Likes clear world rules, distinctive characters, and narratives that honour setup and payoff. Dislikes borrowed mythology used superficially and inconsistent stakes. Prioritises originality and craft; has a high tolerance for complexity but none for lazy explanations.', 0),
  ('fitness_commuter', 'Fitness commuter — high-energy short-form listener', 'commuter', 'A 28-year-old gym-goer in Gurgaon who listens during runs and cab rides. Likes pace, clean scene transitions, and immediate stakes. Dislikes long silences, low-energy openings, and mumbled dialogue. Prioritises momentum, motivation, and a quick emotional hit; has limited patience for stories that take too long to announce themselves.', 0),
  ('domestic_helper', 'Domestic worker — voice-first afternoon listener', 'working_class', 'A 40-year-old domestic worker in Delhi who listens through one earbud between homes. Likes strong voices, easy-to-follow relationships, and humour mixed with feeling. Dislikes complicated non-linear plots and dialogue that assumes elite knowledge. Prioritises respect, security, and care for her children; responds deeply to stories about ordinary people being treated with dignity.', 0),
  ('delivery_partner', 'Delivery partner — mobile late-evening listener', 'working_class', 'A 25-year-old delivery partner in Bengaluru who listens between orders. Likes fast hooks, street-level realism, and characters who keep moving despite pressure. Dislikes slow philosophical scenes and stories that romanticise struggle. Prioritises income, time, and being treated fairly; feels constant pressure from ratings, traffic, and uncertain earnings.', 0),
  ('newlywed', 'Newlywed — relationship-negotiation listener', 'family', 'A 29-year-old newlywed in Ahmedabad setting up a first home. Likes modern relationship stories, playful dialogue, and conflicts resolved through honesty. Dislikes controlling in-laws as cartoon villains and predictable domestic fights. Prioritises partnership, independence, and family acceptance; feels the tension between personal boundaries and pleasing everyone.', 0),
  ('midcareer_manager', 'Mid-career manager — reflective weekend listener', 'professional', 'A 46-year-old manager in Noida who listens on weekend mornings. Likes layered adult characters, ethical dilemmas, and writing that understands offices and marriages. Dislikes simplistic heroes, noisy plot turns, and shallow motivational language. Prioritises relevance, respect, and protecting time outside work; is quietly anxious about career plateau and ageing parents.', 0),
  ('visual_artist', 'Visual artist — mood-sensitive creative listener', 'creative', 'A 32-year-old freelance illustrator in Goa who listens while working. Likes atmosphere, unusual voices, sensory detail, and emotionally daring scenes. Dislikes formulaic dialogue and plots that explain every feeling. Prioritises originality, freedom, and emotional texture; is vulnerable to financial instability and the fear of becoming derivative.', 0),
  ('sunday_family_listener', 'Sunday family listener — shared-speaker household', 'family', 'A 48-year-old father in Patna playing audio aloud while family members move around the room. Likes clean language, accessible humour, and stories with broad emotional appeal. Dislikes explicit content, relentlessly bleak themes, and characters that are hard to distinguish by voice. Prioritises shared enjoyment and a story everyone can follow; values entertainment that does not create awkwardness at home.', 0)
on conflict (id) do update set
  label = excluded.label,
  persona_type = excluded.persona_type,
  prompt = excluded.prompt,
  calibrated_from = excluded.calibrated_from,
  updated_at = now();
